// This file was generated by @ciffi-js/releaser.

import { dirname } from "path";
import { fileURLToPath } from "url";
import { FlatCompat } from "@eslint/eslintrc";
import sonarjs from "eslint-plugin-sonarjs";
import prettier from "eslint-plugin-prettier";

const __filename = fileURLToPath(import.meta.url);
const __dirname = dirname(__filename);

const compat = new FlatCompat({
  baseDirectory: __dirname,
});

const eslintConfig = [
  ...compat.extends(
    "next/core-web-vitals",
    "next/typescript",
    "plugin:prettier/recommended",
    "prettier",
  ),
  {
    plugins: {
      sonarjs,
      prettier,
    },
    rules: {
      // Regole specifiche di SonarJS
      "sonarjs/no-duplicate-string": "warn", // Avvisa se ci sono stringhe duplicate
      "sonarjs/no-identical-functions": "error", // Errore se ci sono funzioni identiche
      "sonarjs/no-small-switch": "warn", // Avvisa se uno switch ha troppo poche casistiche
      "sonarjs/no-collapsible-if": "warn", // Avvisa se if annidati possono essere uniti
      "sonarjs/no-redundant-boolean": "warn", // Avvisa se ci sono condizioni booleane ridondanti
      "sonarjs/no-useless-catch": "warn", // Avvisa se un blocco catch è inutile
      "sonarjs/prefer-single-boolean-return": "warn", // Suggerisce di usare un singolo return booleano
    },
  },
  {
    files: ["*.json", "*.md", "*.css"],
    rules: {},
  },
];

export default eslintConfig;
